version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    links:
    - db
    volumes:
    - .:/app
    - bundle-data:/bundle
    environment: 
      BUNDLE_PATH: /bundle/vendor
      DATABASE_URL: postgres://postgres:password@db/template_development
      DB_HOST: db 
      DB_PASSWORD: password
      PAGER: more
  db:
    image: postgres:12
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: template_development
volumes:
  db-data:
  bundle-data: